ENT/apps/result/urls.py
from django.urls import path

from . import views

app_name = 'result'
urlpatterns = [
	path('', views.index, name='index'),
	path('for_admin/', views.admin, name='manpage'),
	path('admin_page/', views.add_admin, name='add_admin'),
	path('<int:ad_id>/', views.add_std_toadmin, name='add_std_toadmin'),
	path('admin_page/<int:adm_id>/', views.remove_std_fromadmin, name='remove_std_fromadmin'),
	path('add/', views.add_person, name='add_person'),
	path('bb/', views.info, name='info'),
	path('<int:per_id>/', views.add_res, name='add_res'),
	path('bb/<int:tr_id>/', views.add_res_ent, name='add_res_ent')
]

ENT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('result.urls')),
    path('admin/', admin.site.urls),
]

ENT/apps/result/models.py
from django.db import models

import datetime

from django.utils import timezone


# Create your models here.


class Admin(models.Model):
    admin_id = models.IntegerField(unique=True)
    admin_nick = models.CharField("nick", unique=True, null=False, max_length=50)
    admin_password = models.CharField("pass", max_length=50)
    admin_fullname = models.CharField("name", max_length=100)

    def __str__(self):
        return "{} {} {}".format(self.admin_id, self.admin_nick, self.admin_fullname)

    def addStudent(self, st_id):
        std = Person.objects.get(pers_id=st_id)
        std.admin_id = self.admin_id
        std.save()

    def removeStd(self, st_id):
        std = Person.objects.get(pers_id=st_id)
        std.admin_id = 0
        std.save()


class Person(models.Model):
    pers_id = models.IntegerField(unique=True)
    pers_nickname = models.CharField("nick", unique=True, null=True, max_length=50)
    pers_password = models.CharField("passwd", max_length=100)
    pers_fullname = models.CharField("fullname", max_length=50);
    admin_id = models.IntegerField(unique=False, null=False, default=0)
    prof_subject_1 = models.IntegerField(null=True, unique=False, editable=True)
    prof_subject_2 = models.IntegerField(null=True, unique=False, editable=True)
    pers_regdate = models.DateTimeField("date")

    def __str__(self):
        return str(self.pers_id) + " " + self.pers_fullname

    def get_last_ent(self):
        try:
            ent = Trial.objects.filter(trial_pers_id=self.pers_id).order_by('-res_date')[0].trial_res
        except:
            ent="No result"
        return ent

    def get_all_target(self):
        a = self.get_res_last_7days()
        b = str(a[0])
        return b

    def get_all_result(self):
        a = self.get_res_last_7days()
        b = str(a[1])
        return b

    def get_res_last_7days(self):
        b = list()
        for i in Result.objects.filter(res_pers_id=self.pers_id):
            if i.last_7_day():
                b.append(i)
        res = list()
        s1, s2 = 0, 0
        for i in b:
            s1 += i.res_target
            s2 += i.res_done
        res.append(s1)
        res.append(s2)
        return res

    def get_res_last_7days_target(self):
        b = list()
        for i in Result.objects.filter(res_pers_id=self.pers_id):
            if i.last_7_day():
                b.append(i)
        s1 = 0
        for i in b:
            s1 += i.res_target
        return s1

    def get_res_last_7days_done(self):
        b = list()
        for i in Result.objects.filter(res_pers_id = self.pers_id):
            if i.last_7_day():
                b.append(i)
        s1 = 0
        for i in b:
            s1 += i.res_done
        return s1

    def get_last_submit(self):
        b = Result.objects.filter(res_pers_id=self.pers_id).order_by('-res_date')
        if b:
            return b[0].res_date
        return ""

    def get_last_trials_res(self):
        b = Trial.objects.filter(trial_pers_id=self.pers_id).order_by('-res_date')
        if b:
            return b[0].trial_res
        return ""

    def get_last_trials_date(self):
        b = Trial.objects.filter(trial_pers_id=self.pers_id).order_by('-res_date')
        if b:
            return b[0].res_date
        return ""

    def update(self):
        t = Target.objects.filter(target_pers_id=self.pers_id)
        for i in t:
            if int(i.target_targ) < 30:
                i.target_targ += 3
                i.save()


class Trial(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    trial_pers_id = models.IntegerField(unique=False)
    tr_type = models.CharField(max_length=50)
    tr_target = models.IntegerField(unique=False, default=75)
    trial_res = models.IntegerField(unique=False)
    res_date = models.DateTimeField("date of pass", null=True)

    def get_date(self):
        return '{}'.format(self.res_date.strftime('%d.%m.%Y'))


class Subject(models.Model):
    sub_id = models.IntegerField(unique=True)
    sub_name = models.CharField("subject", max_length=50)

    def __str__(self):
        return self.sub_name


class Result(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    res_pers_id = models.IntegerField(unique=False)
    res_sub_id = models.IntegerField(unique=False)
    res_target = models.IntegerField(unique=False)
    res_done = models.IntegerField(unique=False, null=True)
    res_date = models.DateTimeField("date of pass")

    def __str__(self):
        a = Person.objects.get(pers_id=self.res_pers_id)
        x = ' '
        return str(a.pers_id) + " " + a.pers_fullname + '\t' + str(self.res_date)

    def last_7_day(self):
        return self.res_date >= (timezone.now() - datetime.timedelta(days=7))

    def get_subject_name(self):
        return Subject.objects.get(sub_id=self.res_sub_id).sub_name

    def get_date(self):
        return '{}'.format(self.res_date.strftime('%d.%m.%Y'))




class TrialSub(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    trsub_target = models.IntegerField(unique=False, default=15)
    trsub_subid = models.IntegerField(unique=False)
    trsub_res = models.IntegerField(unique=False)
    res_date = models.DateTimeField("date of pass", null=True)

    def get_date(self):
        return '{}'.format(self.res_date.strftime('%d.%m.%Y'))

    def get_subject_name(self):
        return Subject.objects.get(sub_id=self.trsub_subid).sub_name

    def __str__(self):
        return Person.objects.get(id=self.person_id).pers_fullname


class Target(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    target_pers_id = models.IntegerField(unique=False)
    target_sub_id = models.IntegerField(unique=False)
    target_targ = models.IntegerField(unique=False, default=15)
    target_date = models.DateTimeField(null=True)


class TragetEnt(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    target_pers_id = models.IntegerField(unique=False)
    target_sub_id = models.IntegerField(unique=False)
    target_targ = models.IntegerField(unique=False, default=15)
    target_date = models.DateTimeField(null=True)

ENT/apps/result/forms.py
from django import forms

from .models import Person

ENT/apps/result/views.py
import json

from django.shortcuts import render

from django.http import Http404, HttpResponseRedirect, HttpResponse

from .models import Person, Result, Subject, Trial, TrialSub, Target, TragetEnt, Admin

from django.urls import reverse

from django.utils import timezone


def index(request):
    return render(request, 'result/login.html', {"word": ""})


def admin(request):
    return render(request, 'result/admin_login.html', {"word": ""})


def add_admin(request):
    req_id = 1000000
    id = request.POST['username']
    fn = request.POST['nameS']
    if len(id) > 0 and len(fn) > 0:
        try:
            el = Admin.objects.order_by('-admin_id')[0].pers_id + 1
        except:
            el = req_id
        req_id = el
        a = Admin(admin_id=el, admin_nick=id, admin_password=request.POST["pass"],
                  admin_fullname=request.POST["nameS"])
        a.save()
        return info(request, req_id)
    else:
        nick = ''
        try:
            id = int(id)
            req_id = id
        except:
            nick = id
            req_id = Admin.objects.get(admin_nick=nick).admin_id
        try:
            if nick == '':
                a = Admin.objects.get(admin_id=id)
            else:
                a = Admin.objects.get(admin_nick=nick)
        except:
            return render(request, 'result/login.html', {"word": "Не правильный id или никнейм"})
        if a.admin_password == request.POST["pass"]:
            return admin_page(request, req_id)
        else:
            return render(request, 'result/admin_login.html', {"word": "Не правильный пороль"})


def admin_page(request, ad_id):
    try:
        admin = Admin.objects.get(admin_id=ad_id)
        students = Person.objects.filter(admin_id=admin.admin_id)
        to_select = Person.objects.all()
    except:
        return add_admin(request)

    context = {
        "admin": admin,
        "name": admin.admin_fullname,
        "student": students,
        "select": to_select
    }

    return render(request, 'result/admin_info.html', context)


def add_std_toadmin(request, ad_id):
    admin = Admin.objects.get(admin_id=ad_id)
    students = request.POST['std']
    stds = students.split(" ")
    for i in stds:
        if len(i) > 1:
            admin.addStudent(int(i))
    return admin_page(request, ad_id)


def remove_std_fromadmin(request, adm_id):
    admin = Admin.objects.get(admin_id=adm_id)
    students = request.POST['std_rem']
    stds = students.split(" ")
    for i in stds:
        if len(i) > 1:
            admin.removeStd(int(i))
    return admin_page(request, adm_id)


def add_person(request):
    req_id = 1000000
    id = request.POST['username']
    fn = request.POST['nameS']
    if len(id) > 0 and len(fn) > 0:
        el = Person.objects.order_by('-pers_id')[0].pers_id + 1
        req_id = el
        a = Person(pers_id=el, pers_nickname=id, pers_password=request.POST["pass"],
                   pers_fullname=request.POST["nameS"],
                   prof_subject_1=int(request.POST["predmet"].split(" ")[0]),
                   prof_subject_2=int(request.POST["predmet"].split(" ")[2]), pers_regdate=timezone.now())
        a.save()
        Target(target_pers_id=el, target_sub_id=int(request.POST["predmet"].split(" ")[0]), person_id=a.id,
               target_date=timezone.now()).save()
        Target(target_pers_id=el, target_sub_id=int(request.POST["predmet"].split(" ")[2]), person_id=a.id,
               target_date=timezone.now()).save()
        Target(target_pers_id=el, target_sub_id=11, person_id=a.id, target_date=timezone.now()).save()
        Target(target_pers_id=el, target_sub_id=12, person_id=a.id, target_date=timezone.now()).save()
        Target(target_pers_id=el, target_sub_id=13, person_id=a.id, target_date=timezone.now()).save()
        return info(request, req_id)
    else:
        nick = ''
        try:
            id = int(id)
            req_id = id
        except:
            nick = id
            req_id = Person.objects.get(pers_nickname=nick).pers_id
        print("b")
        try:
            print("c")
            if nick == '':
                a = Person.objects.get(pers_id=id)
            else:
                a = Person.objects.get(pers_nickname=nick)
        except:
            return render(request, 'result/login.html', {"word": "Не правильный id или никнейм"})
        print("d")

        if a.pers_password == request.POST["pass"]:
            print("q")
            return info(request, req_id)
        else:
            return render(request, 'result/login.html', {"word": "Не правильный пороль"})


def info(request, id):
    try:
        name = Person.objects.get(pers_id=id)
        subject1 = Subject.objects.get(sub_id=name.prof_subject_1).sub_name
        subject2 = Subject.objects.get(sub_id=name.prof_subject_2).sub_name
        a = Person.objects.all()
        b = Result.objects.all()

        c1 = Target.objects.filter(target_pers_id=id, target_sub_id=11).order_by('-target_date')
        c2 = Target.objects.filter(target_pers_id=id, target_sub_id=12).order_by('-target_date')
        c3 = Target.objects.filter(target_pers_id=id, target_sub_id=13).order_by('-target_date')
        c4 = Target.objects.filter(target_pers_id=id,
                                   target_sub_id=Person.objects.get(pers_id=id).prof_subject_1).order_by('-target_date')
        c5 = Target.objects.filter(target_pers_id=id,
                                   target_sub_id=Person.objects.get(pers_id=id).prof_subject_2).order_by('-target_date')
        c1 = c1[0] if c1 else ""
        c2 = c2[0] if c2 else ""
        c3 = c3[0] if c3 else ""
        c4 = c4[0] if c4 else ""
        c5 = c5[0] if c5 else ""

        tr = Trial.objects.filter(trial_pers_id=id).order_by('-res_date')
        trial = tr if len(tr) > 0 else ""
        tr = tr[0] if tr else ""

        b1 = TragetEnt.objects.filter(person_id=Person.objects.get(pers_id=id).id, target_sub_id=11).order_by(
            '-target_date')
        b2 = TragetEnt.objects.filter(person_id=Person.objects.get(pers_id=id).id, target_sub_id=12).order_by(
            '-target_date')
        b3 = TragetEnt.objects.filter(person_id=Person.objects.get(pers_id=id).id, target_sub_id=13).order_by(
            '-target_date')
        b4 = TragetEnt.objects.filter(person_id=Person.objects.get(pers_id=id).id,
                                      target_sub_id=Person.objects.get(pers_id=id).prof_subject_1).order_by(
            '-target_date')
        b5 = TragetEnt.objects.filter(person_id=Person.objects.get(pers_id=id).id,
                                      target_sub_id=Person.objects.get(pers_id=id).prof_subject_2).order_by(
            '-target_date')
        trial_sub = TrialSub.objects.filter(person_id=Person.objects.get(pers_id=id).id).order_by('-res_date')
        trial_sub = trial_sub if len(trial_sub) > 0 else ""
        b1 = b1[0] if b1 else ""
        b2 = b2[0] if b2 else ""
        b3 = b3[0] if b3 else ""
        b4 = b4[0] if b4 else ""
        b5 = b5[0] if b5 else ""

        res = Result.objects.filter(res_pers_id=id).order_by('-res_date')
        res = res if len(res) > 0 else ""

        data = zip(trial_sub, trial)
    except:
        add_person(request)

    return render(request, 'result/info_student.html',
                  {"data": data, "trial": trial, "trialS": trial_sub, "resOfPers": res, "tr": tr, "tr1": b1, "tr2": b2,
                   "tr3": b3, "tr4": b4, "tr5": b5, "t1": c1, "t2": c2, "t3": c3, "t4": c4, "t5": c5, "person": a,
                   "result": b, "persnickety": name.pers_nickname, "pers": name.pers_id, "name": name.pers_fullname,
                   "sub1": subject1, "sub2": subject2,
                   "id": name.pers_id})


def add_res(request, per_id):
    f = Person.objects.get(pers_id=per_id).id
    a = Result(res_pers_id=per_id, res_sub_id=11,
               res_target=Target.objects.filter(target_pers_id=per_id, target_sub_id=11).order_by('-target_date')[
                   0].target_targ, res_done=request.POST["done1"], res_date=request.POST["date"], person_id=f)
    b = Result(res_pers_id=per_id, res_sub_id=12,
               res_target=Target.objects.filter(target_pers_id=per_id, target_sub_id=12).order_by('-target_date')[
                   0].target_targ, res_done=request.POST["done2"], res_date=request.POST["date"], person_id=f)
    c = Result(res_pers_id=per_id, res_sub_id=13,
               res_target=Target.objects.filter(target_pers_id=per_id, target_sub_id=13).order_by('-target_date')[
                   0].target_targ, res_done=request.POST["done3"], res_date=request.POST["date"], person_id=f)
    d = Result(res_pers_id=per_id, res_sub_id=Person.objects.get(pers_id=per_id).prof_subject_1, res_target=
    Target.objects.filter(target_pers_id=per_id,
                          target_sub_id=Person.objects.get(pers_id=per_id).prof_subject_1).order_by('-target_date')[
        0].target_targ, res_done=request.POST["done4"], res_date=request.POST["date"], person_id=f)
    e = Result(res_pers_id=per_id, res_sub_id=Person.objects.get(pers_id=per_id).prof_subject_2, res_target=
    Target.objects.filter(target_pers_id=per_id,
                          target_sub_id=Person.objects.get(pers_id=per_id).prof_subject_2).order_by('-target_date')[
        0].target_targ, res_done=request.POST["done5"], res_date=request.POST["date"], person_id=f)
    a.save()
    b.save()
    c.save()
    d.save()
    e.save()
    Target(target_pers_id=per_id, target_sub_id=11, person_id=f, target_targ=request.POST["done11"],
           target_date=timezone.now()).save()
    Target(target_pers_id=per_id, target_sub_id=12, person_id=f, target_targ=request.POST["done22"],
           target_date=timezone.now()).save()
    Target(target_pers_id=per_id, target_sub_id=13, person_id=f, target_targ=request.POST["done33"],
           target_date=timezone.now()).save()

ENT/templates/result/admin_info.html
{% extends 'info.html' %}
{% block greeting %}
    <h1>Привет, <span class="name">{{ name }}</span></h1>
{% endblock %}

{% block info %}

<div id="searchDiv" style="display: block; width: 50%; margin: 0 auto;">
<div style="margin-top: 5%" class="container alert alert-info col-md-12">
    <p class="lead">Ваши ученики</p>
</div>

<div class="fixed">
        <input class="form-control" type="text" placeholder="ID" id="search-text" onkeyup="tableSearch()">
        <a id="toSubmitA" href="#asd" class="list-group-item list-group-item-action active col fixed" aria-current="true">На удаление <span id="countofstd"></span></a>
    </div>
<table class="table table-striped" id="info-table">

    <thead>
        <tr>
            <th>ID</th>
            <th>Nickname</th>
            <th>Полное имя</th>
            <th>Цель на 7 дней</th>
            <th>Сделано</th>
            <th>ENT</th>
        </tr>
            {% if student %}
                {% for i in student %}
                    <tr class="alert alert-info" onclick="removeFromAdmin(this, {{ i.pers_id }})">
                        <td class="item"> {{ i.pers_id }} </td>
                        {% if i.pers_nickname %}
                            <td class="item"> {{ i.pers_nickname }} </td>
                        {% else %}
                            <td class="item"> No nick </td>
                        {% endif %}
                        <td class="item"> {{ i.pers_fullname }} </td>
                        <td class="item"> {{ i.get_res_last_7days_target }} </td>
                        <td class="item"> {{ i.get_res_last_7days_done }} </td>
                        <td class="item"> {{ i.get_last_ent }} </td>
                    </tr>
                {% endfor %}
            {% endif %}
    </thead>
    <tbody>
    </tbody>
</table>
<form method="POST" action="{% url 'result:remove_std_fromadmin' admin.admin_id %}">
                                {% csrf_token %}
        <input id="students_rem" class="input100" type="text" name="std_rem" style="display: none">
         <div style="margin-bottom: 5%" id="asd" class="col-md-12 justify-content-center" >
            <button type="submit" class="btn btn-success col-md-12" style="margin: 0 auto">Удалить</button>
        </div>
    </form>
</div>

    <div id="searchDiv" style="display: block; width: 50%; margin: 0 auto;">
    <div style="margin-top: 5%" class="container alert alert-info col-md-12">
    <p class="lead">Добавить учеников</p>
</div>
    <div class="fixed">
        <input class="form-control" type="text" placeholder="ID" id="search-text2" onkeyup="tableSearch2()">
        <a id="toSubmitA" href="#toSubmit" class="list-group-item list-group-item-action active col fixed" aria-current="true">Добавить учеников <span id="addSTD"></span></a>
    </div>

    <table class="table table-striped" id="info-table2">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nickname</th>
            <th>Полное имя</th>
            <th>Цель на 7 дней</th>
            <th>Сделано</th>
            <th>ENT</th>
        </tr>
            {% if select %}
                {% for i in select %}
                    {% if admin.admin_id == i.admin_id %}
                        <tr class="alert alert-success" onclick="add_to_admin(this,{{ i.pers_id  }})">
                            <td class="item"> {{ i.pers_id }} </td>
                            {% if i.pers_nickname %}
                                <td class="item"> {{ i.pers_nickname }} </td>
                            {% else %}
                                <td class="item"> No nick </td>
                            {% endif %}
                            <td class="item"> {{ i.pers_fullname }} </td>
                            <td class="item"> {{ i.get_res_last_7days_target }} </td>
                            <td class="item"> {{ i.get_res_last_7days_done }} </td>
                            <td class="item"> {{ i.get_last_ent }} </td>
                        </tr>
                    {% else %}
                        <tr class="alert alert-info" onclick="add_to_admin(this,{{ i.pers_id  }})">
                            <td class="item"> {{ i.pers_id }} </td>
                            {% if i.pers_nickname %}
                                <td class="item"> {{ i.pers_nickname }} </td>
                            {% else %}
                                <td class="item"> No nick </td>
                            {% endif %}
                            <td class="item"> {{ i.pers_fullname }} </td>
                            <td class="item"> {{ i.get_res_last_7days_target }} </td>
                            <td class="item"> {{ i.get_res_last_7days_done }} </td>
                            <td class="item"> {{ i.get_last_ent }} </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}
    </thead>
    <tbody>
    </tbody>
</table>
    <form method="POST" action="{% url 'result:add_std_toadmin' admin.admin_id %}">
                                {% csrf_token %}
        <input id="students" class="input100" type="text" name="std" style="display: none">
         <div id="toSubmit" class="col-md-12 justify-content-center" >
            <button type="submit" class="btn btn-success col-md-12" style="margin: 0 auto">Добавить</button>
        </div>
    </form>
</div>



    <script type="text/javascript">
        var text=""
        var count = 0
        function add_to_admin(row, pers){
            if (row.classList.contains("alert-success")){
                text = text.substring(0, text.indexOf(pers)) + text.substring(text.indexOf(" ", text.indexOf(pers)+1)+1)
                count--;
                row.classList.add("alert-info");
                row.classList.remove("alert-success");
            }
            else{
                text+=pers+" "
                count++;
                row.classList.remove("alert-info");
                row.classList.add("alert-success");
            }
            document.getElementById("addSTD").textContent = count
            document.getElementById("students").value = text
        }
        var text2=""
        var count2=0
        function removeFromAdmin(row, pers){
            if (row.classList.contains("alert-danger")){
                text2 = text2.substring(0, text2.indexOf(pers)) + text2.substring(text2.indexOf(" ", text2.indexOf(pers)+1)+1)
                count--;
                row.classList.add("alert-info");
                row.classList.remove("alert-danger");
            }
            else{
                text2+=pers+" "
                count2++;
                row.classList.remove("alert-info");
                row.classList.add("alert-danger");
            }
            document.getElementById("countofstd").textContent = count2
            document.getElementById("students_rem").value = text2
        }
        function tableSearch2() {
    var phrase = document.getElementById('search-text2');
    var table = document.getElementById('info-table2');
    var regPhrase = new RegExp(phrase.value, 'i');
    var flag = false;
    for (var i = 1; i < table.rows.length; i++) {
        flag = false;
        for (var j = table.rows[i].cells.length - 1; j >= 0; j--) {
            flag = regPhrase.test(table.rows[i].cells[j].innerHTML);
            if (flag) break;
        }
        if (flag) {
            table.rows[i].style.display = "";
        } else {
            table.rows[i].style.display = "none";
        }

    }
}
    </script>
{% endblock %}

ENT/templates/result/admin_login.html
{% extends 'index.html' %}
{% block title %}
    Admins page
{% endblock %}

{% block form %}
<form class="login100-form" action="{% url 'result:add_admin' %}" method="POST">
    {% csrf_token %}
					<span class="login100-form-logo" style="border-color: red">
						<img width="135px" src="/static/images/ico-removebg-preview.png">
					</span>
					<span class="login100-form-title p-b-34 p-t-27" >
						Log in
					</span>

					<div id="tohide" class="wrap-input100" data-validate = "Enter username">
						<input id="usern" class="input100" type="text" name="username" placeholder="ID или никнейм">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>
					<div  class="wrap-input100" data-validate = "Enter username" style="display: none">
						<input id="predmett" class="input100" type="text" name="predmet" placeholder="ID">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>
					<div  id="reg_id" style = "display: none" >
						<div class="wrap-input100" data-validate = "Enter name, surname">
							<input id="nsur" class="input100" type="text" name="nameS" placeholder="Имя Фамилия">
							<span class="focus-input100" data-placeholder="&#xf207;"></span>
						</div>
					</div>
					<div class="wrap-input100 validate-input"  data-validate="Enter password">
						<input onchange="predy();" class="input100" type="password" name="pass" placeholder="Пороль">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<span id="spann" class="login100-form-title p-b-34 p-t-27" style="color: red; font-size: 15px">
						{{ word }}
					</span>

					<div class="container-login100-form-btn">
						<button onclick="predy()" class="login100-form-btn" type="submit">
							Войти
						</button>
					</div>
					<div  class="container-login100-form-btn"  >
						<button type="button" id="reg-back" class="login100-form-btn" onclick="reg_form()" >
							Регистрация
						</button>
					</div>
				</form>
{% endblock %}